apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: feide-credentials
  namespace: phis
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: feide-credentials   # must match secretKeyRef.name in deployment.yaml
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: feide-client-id
    - secretKey: client-secret
      remoteRef:
        key: feide-client-secret
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ghcr-pull-secret
  namespace: phis
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: ghcr-pull-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .dockerconfigjson }}"
  data:
    - secretKey: dockerconfigjson
      remoteRef:
        key: ghcr-pull-secret-json
