---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: feide-credentials
  namespace: phis
spec:
  encryptedData:
    client-id: AgCvWxZUqg6umDBQotVDdRTamfg5mNaXUVy4SZvc04PHkzieGNOFbPG7S1O1+3Z/C81bbvMI7A6X0jma97cHJAcsI7X7dMHnGabYMvXBomvXLw1HE4ih9fvzoD2vGjBvM3oB8+WkjBFRV1pJg3/bpvY4dwaJ1qiBVROomLj3MFs9s0OXeFndkU/iEfUOoPCW5QU9kh3fBQ7O7XZrxQtD+gTFHFVqFxhHHLZIV3AQUbxsqT49HPfmaTYVGnEIqT7jatdpPFI11+OwOhN1x/HDEifHPQoh34uliud7G2SlF35yJ9pb129UvmtOArwi/A3RC0oJQieI/ujEqiQkGtgpA32E+MARvaIbsy3FXqvtxHtdIafiW1wbD9VvWwXGTn13GCp2/e42QYyzrECmqafBmmgaTViDkNp9AQMPJGm8++71oji4NM1z/wE3mxu8xt7uXPcpKVP6MNw8DruM+v7Upk/1PorANCvda/DX1jkTJ1FzvWMxFc6mIijlskpMB01fnwJ7p87GR6RlYRqtIm1Q25P/9S4v0oIShBcw3b4LWgvyp8S6nADiLplSb7fQJ1jhXel83q4gqD5RY5fGTxXwzq7D4ku8Ez/up+TMe3cIQJYYOghORN/DGDcXf8YXXwP2aQT4zN5ZksQ5+Lv8mEh0Xu9l+DgQW3nqXQkicHR15yOUVU3AFM5r6E3WgaL7AMS9cZl/fCsGGFxqO9rAW0lkDgofAy2lQky4WcCUkU8nRanlS0gT6ns=
    client-secret: AgBegx17byc74jZN9LvWts3zf7USzyUN5j5kWjKdSIvf+9NKiMS4SmGW62aPvWZC6dflUhjN0jpF6dCR1owpQZrslLsgS8lq7f8pO1F0u5pU6NGQKDueUHZ82ILYIqeX7pfRLVTvj2Q22Rw+YEdq1GUWoZRq50VgIowH7kO1HeiTnjzRrLiv2FREJqyTDQ9m+IbyNlzFAJQmwc8Hi/QKK5it8g1lO+solDO0/f8UjLZXqqoOpIi0XfkVC/C6THsQ1Q0CiXhsJNd/QYMKiWAjYCVqdcTNTwE+0D2JDRMA/B7+ShgQZPZJqFfe9F8xDvc1gvUlU/D550go9TWemBp4dg+sdgMevjg3BFOKroDOOIekxyZUdhYmptAYOWh5/qEccg7ie0W0UDU3lKXO3+a+lbMLK8gY2r5I5zEU7UwpwE9+2QqcEmDHO6zdSgdnKlJr9u+YsWdvWKIN1uCvIznVYYXd327GOu0ntbSXRE8UMHLX7Xmc38HJK5j6WTH0GgThRbcGXuLOVndYXdkAKWBbdROC0wawj95D9f6PacYg+oKLsaOyucMUNW3Y1xkbRtPZOerEbxEbQ6ffb2e+Kms4HO9qgcS3qpnaFfRXhwCYbCXXKJmk+FVeSBeL6QhSarS41ofB5bJeC61qq4P/PuVqhIAsvecWONkBd6df2Svv64J4NA4euS+92rkqvZcjnv86wSXFqcMFWarX4Icq1s9akldXvyZ+h+RhIj73VNeLlzFdb2msysg=
  template:
    metadata:
      creationTimestamp: null
      name: feide-credentials
      namespace: phis
