apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opensilex-data
  namespace: phis
spec:
  storageClassName: azureblob-fuse2-phis
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
