apiVersion: v1
kind: PersistentVolume
metadata:
  name: graphdb-backup-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azureblob-fuse2-backup
  mountOptions:
    - -o allow_other
    - --file-cache-timeout-in-seconds=0
  csi:
    driver: blob.csi.azure.com
    readOnly: false
    volumeHandle: phis-graphdb-backups
    volumeAttributes:
      resourceGroup: phis-rg
      storageAccount: phistfstate
      containerName: graphdb-backups
      protocol: fuse2
