apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: phis

resources:
  - mongodb-backup-pv.yaml
  - mongodb-backup-pvc.yaml
  - mongodb-cronjob.yaml
  - graphdb-backup-pv.yaml
  - graphdb-backup-pvc.yaml
  - graphdb-cronjob.yaml
