apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-backup-pvc
  namespace: phis
spec:
  storageClassName: azureblob-fuse2-backup
  volumeName: mongodb-backup-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
