apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: graphdb-credentials
  namespace: phis
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: graphdb-credentials   # must match secretKeyRef.name in deployment.yaml
    creationPolicy: Owner       # ESO deletes the K8s secret if this CR is deleted
  data:
    - secretKey: admin-password          # key in the resulting K8s Secret
      remoteRef:
        key: graphdb-admin-password      # name in Azure Key Vault
