apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: graphdb-data
  namespace: phis
spec:
  # ReadWriteOnce: only one node can mount this volume at a time.
  # This is fine for a single-replica Deployment.
  storageClassName: managed-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
