---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: graphdb-credentials
  namespace: phis
spec:
  encryptedData:
    admin-password: AgBNjxX7mXTOpF6Cfr6mWGjfrU4lm2GyhcQBTCWffH7qnKRLpI665pjVop9VdrruWFLGzj892Nrn1tMc0gC4nhRxCQLh6jPz9wrzYsO/kR3Ghw1jOduM0wZYl0oG++16KgJlTZ43QeBeDPFU0xza9xUU8dW3PSZjZ2at3tTSQT94r1qWrTc2DTCyjcEy1Xo/V12yfpzMZb5P12TBwEr6XHqh4KcOoAmx7smqoHXcNhs/M0BQ3wRi3Zr9LAHWbcsm2pmZhFyFZqytl4Qyy5DpEt2cv3I5u2Dy0WG3wtwLbOCAvCZ3PUa4DWI509LOJs5fY8QeaoLvMHoiRx8/n68aqfg9JdNeG+84/s/vsKoC7CQKeAb69Z+pCIFG9Kbe27uCSA+vwpvtmCZYmCdMoilVGCgH+pS34ozoz+ECjHVKuwTH34w9ndq6LGu0Jybd29R2LzDZ7RAi/sf4yrhPZ/G8ZgxUJqIn0aAG4Sp7RZd3JXJ3chlF9nzhqd7rFukf7QwXP1Lg41volU8xbjqguCH9gTiiTZCRrqkp49R4z33aV6cC4tw74IWvM2pOBiXNXP94eicDwNNGJeSqrPsWZ1KrB/TRUkUaagiMWn20x63q3USGodMQSipqDPAMfoUrMo72qytSUgG/tYSI5FhS83OQg4JnvqD72pSBjGpj0Qk1fZ++TbjEiNTcnNtrwJv9IJtEuOAyZCRPz02NjiJoejl8K32KUvj6BXElesvCoJc+Nrc7QNoELJkyzaDZB1oJ7A==
  template:
    metadata:
      creationTimestamp: null
      name: graphdb-credentials
      namespace: phis
    type: Opaque
